name: Hello World

on: 
  push:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, GitHub Actions!"
        
      - name: Print Docker Version
        run: docker version
        
      - name: AWS STS Get Caller Identity
        run: aws sts get-caller-identity

      - name: Check S3 buckets list
        run : aws s3 ls
